owner: differental
repo: status

sites:
  - name: Portfolio
    url: $PF_URL
  - name: Blog
    url: $BLOG_URL
  - name: Portfolio (Mirror)
    url: $PF_BAK_URL
  - name: Enviame (Production)
    url: $ENVIAME_PROD_URL
  - name: Enviame (Beta)
    url: $ENVIAME_BETA_URL
  - name: ErgTools
    url: $ET_URL
  - name: HedgeDoc
    url: $HD_URL

status-website:
  cname: status.brianc.tech
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status
  introTitle: "Real-time status of brianc.tech services."
  introMessage: This website displays the real-time status records of web services hosted on brianc.tech
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: night

assignees:
  - differental

skipDeleteIssues: true

user-agent: differental
